import React from 'react';
import ReactDOM from 'react-dom';
import App from './App.jsx';
import App2 from './App2.jsx';
import App3 from './App3.jsx';
import App4 from './App4.jsx';
import App5 from './App5.jsx';
import App6 from './App6.jsx';
import App7 from './App7.jsx';
import App8 from './App8.jsx';

ReactDOM.render(<App />, document.getElementById('app'));
ReactDOM.render(<App2 />, document.getElementById('app2'));
//ReactDOM.render(<App3 headerProps="Header props" contentProps="Content Props"/>, document.getElementById('app3'));
ReactDOM.render(<App3 />, document.getElementById('app3'));
ReactDOM.render(<App4 />, document.getElementById('app4'));
ReactDOM.render(<App5 />, document.getElementById('app5'));
ReactDOM.render(<App6 />, document.getElementById('app6'));
ReactDOM.render(<App7 />, document.getElementById('app7'));
ReactDOM.render(<App8 />, document.getElementById('app8'));